### ISSUE TITLE
clear "OK" in footer?

### ISSUE THREAD

**Issue by thearabbit** [hitchcott/ez-modal#3]
how to cleare `OK` in footer?

**Comment by IstoraMandiri** [comment]
Right now the best way to do it is to pass a `template` option and use your own template

```
// client.js
EZModal({
  template: 'myTemplate'
});

// client.html
<template name='myTempalte'>
  <h1>Where's my footer gone?</h1>
</template>
```

Not very "E-Z" I guess, i'll implement an easier way when I make some updates tomorrow.

**Comment by IstoraMandiri** [comment]
In 0.1.3 you can now use `hideFooter: true` to hide the buttons area entirely.
