### ISSUE TITLE
set height with full screen?

### ISSUE THREAD

**Issue by thearabbit** [hitchcott/ez-modal#4]
Look great, for quickly update.
I want to use modal in modal (multi level pop-up), but when i close the second modal the first modal don't work with scroll bar. so now i would like to set `height` to full screen (don't have scroll bar) to fix this.
Pl help me.

**Comment by IstoraMandiri** [comment]
Hi @yuomtheara 

Take a look at http://stackoverflow.com/questions/18432394/how-to-make-twitter-bootstrap-modal-full-screen. 

You're likely to find better answers for these types of questions on google or stackoverflow. Kindly keep future issues on this repo specific to EZ Modal. Cheers!
