### ISSUE TITLE
how to hide the current modal

### ISSUE THREAD

**Issue by ghost** [hitchcott/ez-modal#7]
I want to hide my madal from somewhere else on the code. not inside of the `rightButtons` or `leftButtons`. so i can't use `this.EZModal.modal('hide')`

**Comment by SenerDemiral** [comment]
It is bootstrap modal

```
$('.modal').modal('hide');
```

**Comment by ghost** [comment]
@SenerDemiral  ok so i am guessing that cleans up everything and destroys the templates?.

**Comment by SenerDemiral** [comment]
Yes, not diferent then clicking close button.

**Comment by IstoraMandiri** [comment]
@MurWade @SenerDemiral is correct.

It's also using `Blaze.remove` on the `hidden` event (which is also triggered by `hide`) to clean everything up.
