### ISSUE TITLE
Question: How to get started?

### ISSUE THREAD

**Issue by pacificanfog0** [hitchcott/ez-modal#8]
I'm trying to use ez-model, but since I'm new to Meteor in general, the examples you have aren't making much sense to me.
I'm stuck on just where to put this code, eg. 

```
EZModal 'Hello World'
```

What file do I put this code in? We could take a starting place of the simple to do list https://github.com/meteor/simple-todos

In the file simple-todos.js, if I put

```
"submit .new-task": function (event) {
    EZModal 'Hello World'
    ....
}
```

I am getting syntax errors. There's something I'm missing here.

**Comment by IstoraMandiri** [comment]
Hi. The examples are written in coffeescript.  You'd need to convert it to javascript if you're writing in JS.

For example, `EZModal 'Hello world'` becomes `EZModal('Hello world')`.
